### ISSUE TITLE
is_windows not defined?

### ISSUE THREAD

**Issue by chtenb** [sravioli/wezterm#1]
Hey, cool term config! I tried to adopt it, but I notice that the is_windows functions is not defined in the utils/fun module?

**Comment by sravioli** [comment]
Hey, thanks! Yes looks like the `is_windows()` is missing.  I probably did not commit the change and lost it since I've formatted my machine.

**Comment by sravioli** [comment]
oops closed by accident. I pushed v3.0.1 that adds the is_windows function
