### ISSUE TITLE
[BUG] Problem with update-status event

### ISSUE THREAD

**Issue by kahilah** [sravioli/wezterm#15]
Module fails with the following error message:

```
23:03:37.801  ←[31mERROR ←[0m ←[1mwezterm_gui::termwindow←[0m > while processing update-status event: runtime error: C:\Users\xxx\.config\wezterm/events\update-status.lua:24: attempt to index a nil value (local 'theme')
stack traceback:
        C:\Users\xxx\.config\wezterm/events\update-status.lua:24: in function <C:\Users\xxx\.config\wezterm/events\update-status.lua:18>
```

I used nightly build and tested with latest stable bulid as well.

**To Reproduce**
Followed README

**Comment by sravioli** [comment]
The config is unable to find the wezterm theme. Does reloading Wezterm fixes it?

**Comment by kahilah** [comment]
After setting up my own wezterm configuration file, this problem disappeared. Will reopen if further problems appear.
