### ISSUE TITLE
Can't set window_background_opacity  property.

### ISSUE THREAD

**Issue by magicmayu** [sravioli/wezterm#16]
When i use this config, I can't set window_background_opacity.
```lua
color.set_tab_button(Config, theme)

Config.window_background_opacity = 0.9

return Config
```
I added this settting in the appearance.lua. But it did't work.

**Comment by sravioli** [comment]
This is because the config sets the background:

~~~lua
Config.background = {
  {
    source = { Color = theme.background },
    width = "100%",
    height = "100%",
  },
}
~~~

just add the opacity field there:

~~~diff
Config.background = {
  {
    source = { Color = theme.background },
    width = "100%",
    height = "100%",
+   opacity = 0.9,
  },
}

~~~

**Comment by sravioli** [comment]
I just realized that the `Utils.fn.color.set_sheme()` function overrides the backround config. I'm pushing a fix that allows the user to set the background opacity using `wezterm.GLOBAL.opacity`
