### ISSUE TITLE
Issue with battery icon

### ISSUE THREAD

**Issue by akthe-at** [sravioli/wezterm#2]
First, I just wanted to say thanks to you for posting your config. I've been using it for quite awhile now and I use it as the foundation for my own.

However, before and after the current update I still have an issue with the battery icon mapping. It all seems to come down to this line:
 `battery.ico = icons.Battery[battery.state][tostring(battery.lvl_round)]`
the config just seems unable to map this line back to the utils/icons.lua information. I believe it is an issue with how my  computer reports the battery level when it is plugged in and at 100% charge. (battery.state == "Full",  battery.lvl_round ==100).

Writing this issue made me think of a fix (I added a tiny segment to the M.Battery table) and that seems to have fixed it!

```
  Full = {
    ["100"] = wez.nerdfonts.md_battery,
  },
```

**Comment by sravioli** [comment]
Hey, thanks for the kind words! Looks like wezterm reports the battery state as Full, instead of charging/discharging when it's at 100%. 

I'll look at the PR now
