### ISSUE TITLE
[BUG] Performance Issue

### ISSUE THREAD

**Issue by akthe-at** [sravioli/wezterm#8]
**Describe the bug**
This is not the most clear bug report but have you noticed any strange lag/performance hiccups since the introduction of a lot of the changes? I added a lot of changes at once so  I didn't get a good feel for where/when it started. I did notice that you commented out the format-tab-title code with a comment of performance issues. However, even with that commented out I noticed a strange lag with certain things. 

I think it is most noticeable when saving changes to the config.

**To Reproduce**
1. Go to any file in the config and make an edit or comment.
2. Save the changes.
3. Let Wezterm hot reload the changes to the config.
4. On Windows I get a lot of window resizing/flashing when the config is changed/reloaded.

**Expected behavior**
I don't think I ever recall having anything like this in the past when applying changes/config overrides/etc.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Wezterm Nightly

**Comment by sravioli** [comment]
Yup. Sadly I experienced the same thing. I haven't tested Windows since I basically only use Linux with Wayland tho. I noticed a bit of lag on startup and some lag upon config save. I also experienced (maybe quadratic?) increase in lag for each open tab: typing (or doing anything else) would get basically impossible.

I think this has a lot to do with the introduction of the theme picker.  I've read that `wezterm.color.get_builtin_schemes()` is very expensive and I think that that is the culprit. [Here](https://github.com/wez/wezterm/issues/4788) is the issue regarding this.

I was experimenting with caching the themes in a folder/file as some minified Lua tables to avoid calling that function.

For some reason `update-tab-title` and `wezterm.color.get_builtin_schemes()` are performance killers.

**Comment by akthe-at** [comment]
Yeah it seems like you need to have one expensive call to the built in function, and then a less expensive lookup call that is used more frequently when updating/repainting the UI. How to implement that idea is what I am mulling around in my head right now...

The other alternative is to having a smaller curated list of themes to choose from but would require manual compilation it seems.

**Comment by sravioli** [comment]
Yes exactly, I couldn't get to work `wezterm.GLOBAL` otherwise I would've cached it there. 

The lookup I think would be similar to the one we do for fonts.

**Comment by akthe-at** [comment]
Do you think Kevin Silverster's use of GLOBAL for his backdrops could help you to figure it out? https://github.com/KevinSilvester/wezterm-config/blob/master/utils/backdrops.lua

**Comment by sravioli** [comment]
I'll take a look this afternoon, thank you :)

**Comment by sravioli** [comment]
@akthe-at 
I've done some heavy refactoring of the config. The tab-bar event can be enabled again. I'll push all the updates to a new branch (refactor/picker)

**Comment by sravioli** [comment]
I've basically got rid of `wezterm.colors.get_builtin_schemes()`, it causes a big performance hit and it does not justify it's use. I much prefer adding few handcrafted themes instead of a bunch of them that impact performance.

**Comment by akthe-at** [comment]
I am excited to try it out and I can totally agree with and get on board with the thinking behind nixxing get_builtin_schemes...The thing with the builtin schemes is that their color ordering doesn't always make for the best implementation in this config either.

**Comment by sravioli** [comment]
Yeah.. I've even implemented a function to add the missing values that we use:

```lua
M.color.add_tab_bar = function(colors)
  colors.tab_bar = {
    background = colors.cursor_fg or colors.background,
    active_tab = { bg_color = colors.ansi[5], fg_color = colors.background },
    inactive_tab = { bg_color = colors.brights[1], fg_color = colors.background },
    inactive_tab_hover = {
      bg_color = colors.selection_bg,
      fg_color = colors.brights[1],
      italic = true,
    },
    new_tab = { bg_color = colors.brights[1], fg_color = colors.background },
    new_tab_hover = {
      bg_color = colors.split,
      fg_color = colors.background,
      italic = true,
    },
  }

  return colors
end
```

and I've even wrote a function to dump each theme in a file. No performance improvement sadly :(

**Comment by akthe-at** [comment]
:\ I was trying to think of alternatives like even maybe using a sqlite db file or something... Did you push your new branch yet?

**Comment by sravioli** [comment]
> :\ I was trying to think of alternatives like even maybe using a sqlite db file or something... Did you push your new branch yet?

I'm commiting rn. Should be a matter of minutes

**Comment by sravioli** [comment]
@akthe-at The branch is live! Sorry for the wait. I didn't have time to re-implement the font picker but it's no hard task. I'll probably do it tomorrow.

LMK if performance has improved, on my machine I can feel a speed-up compared to the `main` branch

**Comment by akthe-at** [comment]
@sravioli Currently the new changes aren't working...I think there is a pathing issue somewhere due to dumb windows paths...trying to figure out where...

```
runtime error: C:\Users\ARK010\.config\wezterm/utils\class\picker.lua:187:
module '' not found:
        no field package.preload['']
        no file 'C:\Users\ARK010\scoop\apps\wezterm-
nightly\current\wezterm_modules/.lua'
        no file 'C:\Users\ARK010\scoop\apps\wezterm-nightly\current\wezterm_modules//
init.lua'
        no file 'C:\Users\ARK010\.config\wezterm/.lua'
        no file 'C:\Users\ARK010\.config\wezterm//init.lua'
        no file 'C:\Users\ARK010\AppData\Roaming\wezterm/plugins//plugin/init.lua'
        no file 'C:\Users\ARK010\.wezterm/.lua'
        no file 'C:\Users\ARK010\.wezterm//init.lua'
        no file 'C:\Users\ARK010\scoop\apps\lua51\current'

        can't load C modules in safe mode
stack traceback:
        [C]: in function 'require'
        C:\Users\ARK010\.config\wezterm/utils\class\picker.lua:187: in function
'utils.class.picker.register'
        C:\Users\ARK010\.config\wezterm/utils\class\picker.lua:180: in function
'utils.class.picker.new'
        C:\Users\ARK010\.config\wezterm/picker\colorscheme.lua:8: in main chunk
        [C]: in function 'require'
        C:\Users\ARK010\.config\wezterm/mappings\modes.lua:155: in main chunk
        [C]: in function 'require'
        C:\Users\ARK010\.config\wezterm/mappings/init.lua:3: in main chunk
        [C]: in function 'require'
        C:\Users\ARK010\.config\wezterm/utils\class\config.lua:53: in function
'utils.class.config.add'
        (...tail calls...)
```

**Comment by akthe-at** [comment]
I can tell that the tab bar is much more performant but the io.popen is just not well received by Windows.  I think we might be able to get some functionality out of wezterm.read_dir but I wonder if the issue is how it is wrapped/nested. Maybe we need to read the dirs that we need and store the results somewhere, and then call those results where needed?

**Comment by sravioli** [comment]
> @sravioli Currently the new changes aren't working...I think there is a pathing issue somewhere due to dumb windows paths...trying to figure out where...
> 
> ```
> runtime error: C:\Users\ARK010\.config\wezterm/utils\class\picker.lua:187:
> module '' not found:
>         no field package.preload['']
>         no file 'C:\Users\ARK010\scoop\apps\wezterm-
> nightly\current\wezterm_modules/.lua'
>         no file 'C:\Users\ARK010\scoop\apps\wezterm-nightly\current\wezterm_modules//
> init.lua'
>         no file 'C:\Users\ARK010\.config\wezterm/.lua'
>         no file 'C:\Users\ARK010\.config\wezterm//init.lua'
>         no file 'C:\Users\ARK010\AppData\Roaming\wezterm/plugins//plugin/init.lua'
>         no file 'C:\Users\ARK010\.wezterm/.lua'
>         no file 'C:\Users\ARK010\.wezterm//init.lua'
>         no file 'C:\Users\ARK010\scoop\apps\lua51\current'
> 
>         can't load C modules in safe mode
> stack traceback:
>         [C]: in function 'require'
>         C:\Users\ARK010\.config\wezterm/utils\class\picker.lua:187: in function
> 'utils.class.picker.register'
>         C:\Users\ARK010\.config\wezterm/utils\class\picker.lua:180: in function
> 'utils.class.picker.new'
>         C:\Users\ARK010\.config\wezterm/picker\colorscheme.lua:8: in main chunk
>         [C]: in function 'require'
>         C:\Users\ARK010\.config\wezterm/mappings\modes.lua:155: in main chunk
>         [C]: in function 'require'
>         C:\Users\ARK010\.config\wezterm/mappings/init.lua:3: in main chunk
>         [C]: in function 'require'
>         C:\Users\ARK010\.config\wezterm/utils\class\config.lua:53: in function
> 'utils.class.config.add'
>         (...tail calls...)
> ```
> 

Dang it! I think this is caused by the dir command inside the `M.fs.read_dir()` function

**Comment by sravioli** [comment]
> I can tell that the tab bar is much more performant but the io.popen is just not well received by Windows. 

I noticed that Wezterm is much less performant on windows for some reason. Opens basically instantly on Arch/Fedora (Linux I used) and took a bit more on Win11. Sadly `io.popen()` is not good for Windows.

> I think we might be able to get some functionality out of wezterm.read_dir but I wonder if the issue is how it is wrapped/nested. Maybe we need to read the dirs that we need and store the results somewhere, and then call those results where needed?

My guess is that the error we get when calling `wezter.read_dir()` is caused by the loop used to process keymaps (in `mappings/modes.lua`).
We could read directories on wezterm startup and cache the file lists as `wt.GLOBAL` values? 

I think that's possible but would require some changes to the Picker logic.

**Comment by akthe-at** [comment]
> > I can tell that the tab bar is much more performant but the io.popen is just not well received by Windows.
> 
> I noticed that Wezterm is much less performant on windows for some reason. Opens basically instantly on Arch/Fedora (Linux I used) and took a bit more on Win11. Sadly `io.popen()` is not good for Windows.
> 
> > I think we might be able to get some functionality out of wezterm.read_dir but I wonder if the issue is how it is wrapped/nested. Maybe we need to read the dirs that we need and store the results somewhere, and then call those results where needed?
> 
> My guess is that the error we get when calling `wezter.read_dir()` is caused by the loop used to process keymaps (in `mappings/modes.lua`). We could read directories on wezterm startup and cache the file lists as `wt.GLOBAL` values?
> 
> I think that's possible but would require some changes to the Picker logic.

I  think you are spot on with the builtin read_dir and wt.GLOBAL need. I didn't realize I was actually doing this already in my mix and match version of your config with Kevin's backdrop stuff. His comments even explained it all...oops.

```
--- Initialise backdrop controller
---@private
function BackDrops:init()
  local inital = {
    current_idx = 1,
    files = {},
  }
  local backdrops = setmetatable(inital, self)
  wezterm.GLOBAL.background = nil
  return backdrops
end

---MUST BE RUN BEFORE ALL OTHER `BackDrops` functions
---Workaround to set the `files` after instantiating `BackDrops`.
---Wezterm's fs utilities `read_dir` and `glob` work by running on a spawned child process.
---This throws a coroutine error if either of these functions are invoked in outside of `wezterm.lua`
---in the initial load of the Terminal config
function BackDrops:set_files()
  self.files = wezterm.read_dir(wezterm.config_dir .. PATH_SEP .. "backdrops")
  wezterm.GLOBAL.background = self.files[1]
  return self
end
```

my wezterm.lua:
```
---class @Config
local Config = require("utils.class.config"):new()

require("utils.backdrops"):set_files():random()
require "events.update-status"
require "events.format-tab-title"
require "events.new-tab-button-click"
require "events.augment-command-palette"
require "sessionizer"
require "wezterm-session-manager/session-manager"

return Config:add("config"):add "mappings"
```

**Comment by akthe-at** [comment]
Also...Yeah Windows can be quite limiting in a lot of ways but it is forced on me for work :\

**Comment by sravioli** [comment]
> > > I can tell that the tab bar is much more performant but the io.popen is just not well received by Windows.
> > 
> > I noticed that Wezterm is much less performant on windows for some reason. Opens basically instantly on Arch/Fedora (Linux I used) and took a bit more on Win11. Sadly `io.popen()` is not good for Windows.
> > 
> > > I think we might be able to get some functionality out of wezterm.read_dir but I wonder if the issue is how it is wrapped/nested. Maybe we need to read the dirs that we need and store the results somewhere, and then call those results where needed?
> > 
> > My guess is that the error we get when calling `wezter.read_dir()` is caused by the loop used to process keymaps (in `mappings/modes.lua`). We could read directories on wezterm startup and cache the file lists as `wt.GLOBAL` values?
> > 
> > I think that's possible but would require some changes to the Picker logic.
> 
> I  think you are spot on with the builtin read_dir and wt.GLOBAL need. I didn't realize I was actually doing this already in my mix and match version of your config with Kevin's backdrop stuff. His comments even explained it all...oops.
> 
> ```
> --- Initialise backdrop controller
> ---@private
> function BackDrops:init()
>   local inital = {
>     current_idx = 1,
>     files = {},
>   }
>   local backdrops = setmetatable(inital, self)
>   wezterm.GLOBAL.background = nil
>   return backdrops
> end
> 
> ---MUST BE RUN BEFORE ALL OTHER `BackDrops` functions
> ---Workaround to set the `files` after instantiating `BackDrops`.
> ---Wezterm's fs utilities `read_dir` and `glob` work by running on a spawned child process.
> ---This throws a coroutine error if either of these functions are invoked in outside of `wezterm.lua`
> ---in the initial load of the Terminal config
> function BackDrops:set_files()
>   self.files = wezterm.read_dir(wezterm.config_dir .. PATH_SEP .. "backdrops")
>   wezterm.GLOBAL.background = self.files[1]
>   return self
> end
> ```
> 
> my wezterm.lua:
> ```
> ---class @Config
> local Config = require("utils.class.config"):new()
> 
> require("utils.backdrops"):set_files():random()
> require "events.update-status"
> require "events.format-tab-title"
> require "events.new-tab-button-click"
> require "events.augment-command-palette"
> require "sessionizer"
> require "wezterm-session-manager/session-manager"
> 
> return Config:add("config"):add "mappings"
> ```

Interesting... I Sadly cannot work on the config this weekend. I'll be taking a look Monday

**Comment by sravioli** [comment]
@akthe-at I've just fixed the `runtime error: C:\Users\ARK010\.config\wezterm/utils\class\picker.lua:187:` by changing the dir command. I've tested briefly by booting Win11 on my machine and it seems to work.

Keep in mind that LOTS of terminal popups will happen when reloading the config since that aspect has not been fixed yet

**Comment by sravioli** [comment]
Regarding the terminal windows popup I think we can either:

- cache the result of the `M.fs.read_dir()` in a `wt.GLOBAL` field
- update the config to use `wt.read_dir()`
- do both by wrapping `wt.read_dir()` to cache read values

**Comment by akthe-at** [comment]
Works like a charm now and the pickers are back to working, very nice! I tried to implement a version of the global stuff last night but fell asleep... I was not having a ton of luck with logical reasoning with how tired I was... 😂😂

**Comment by sravioli** [comment]
> ```lua
>   local handle = io.popen(cmd)
>   if not handle then
>     return
>   end
>   local result = handle:read "*a"
>   handle:close()
> 
>   local files = {}
>   for file in result:gmatch "[^\r\n]+" do
>     if not file:match "init%.lua$" then
>       files[#files + 1] = file
>     end
>   end
> 
>   return files
> end
> ```
> 
> I'm not the best with regex but are we reading the contents of the file with io.popen just to check that the file name isn't init.lua?

We don't read the file contents, we are executing the command and reading its output, then parse it (each line is a path) and exclude any `init.lua` file that may be present in the directory (maybe in the future we might want to do something special with the `init.lua` file).

**Comment by sravioli** [comment]
> Well I think read_dir of either type is is fine now, it's only the reading of the files in the directory that's causing me an issue right now via `io.popen()`. I think we could approach the reading of the files differently like we started talking about in the closed font picker PR we could get somewhere


We could have an `init.lua` file like the one in the `colors` folder in the `main` branch, but that's not automatic anymore.

I really like the idea of not having to maintain a separate `init.lua` file

**Comment by sravioli** [comment]
We could move the key table loop to `wezterm.lua` and use the builtin `wt.read_dir()`?

**Comment by akthe-at** [comment]
> We could move the key table loop to `wezterm.lua` and use the builtin `wt.read_dir()`?

We could do that or we could add an external dependency like fd or find to the process? In my sessionizer script I look for git dirs with fd and bypass using io.popen combined with cmd but it would require the use of fd or find and a more manual config setup...Here is an example of that

```lua
local wezterm = require "wezterm"
local act = wezterm.action
local fun = require "utils.fn"
local M = {}

--- Converts Windows backslash to forwardslash
---@param path string
local function normalize_path(path)
  return fun.fs.platform().is_win and path:gsub("\\", "/") or path
end

local home = normalize_path "C:/Users/ARK010/"

--- If name nil or false print err_message
---@param name string|boolean|nil
---@param err_message string
local function err_if_not(name, err_message)
  if not name then
    wezterm.log_error(err_message)
  end
end
--
--- path if file or directory exists nil otherwise
---@param path string
local function file_exists(path)
  if path == nil then
    return nil
  end
  local f = io.open(path, "r")
  -- io.open won't work to check if directories exist,
  -- but works for symlinks and regular files
  if f ~= nil then
    wezterm.log_info(path .. " file or symlink found")
    io.close(f)
    return path
  end
  return nil
end

-------------------------------------------------------
-- PATHS
--
local fd = (
  file_exists(home .. "/bin/fd")
  or file_exists "usr/bin/fd"
  or file_exists(home .. "/bin/fd.exe")
  or file_exists "C:\\Users\\ARK010\\scoop\\shims\\fd.exe"
)
err_if_not(fd, "fd not found")

local git = (
  file_exists "C:/Users/ARK010/scoop/apps/git/current/bin/git.exe"
  or file_exists "/usr/bin/git"
)
err_if_not(git, "git not found")

local srcPath = home .. "Documents"
err_if_not(srcPath, srcPath .. " not found")

local search_folders = {
  srcPath,
  srcPath .. "/DEM",
  home .. "/.plugins/",
  home .. "/.config/",
  -- srcPath .. "/other",
}
-------------------------------------------------------

--- Merge numeric tables
---@param t1 table
---@param t2 table
---@return table
local function merge_tables(t1, t2)
  local result = {}
  for index, value in ipairs(t1) do
    result[index] = value
  end
  for index, value in ipairs(t2) do
    result[#t1 + index] = value
  end
  return result
end

M.start = function(window, pane)
  local projects = {}

  -- assumes  ~/src/www, ~/src/work to exist
  -- ~/src
  --  ├──nushell-config       # toplevel config stuff
  --  ├──wezterm-config
  --  ├──work                    # work stuff
  --    ├──work/project.git      # git bare clones marked with .git at the end
  --    ├──work/project-bugfix   # worktree of project.git
  --    ├──work/project-feature  # worktree of project.git
  --  │ └───31 unlisted
  --  └──other                # 3rd party project
  --     └──103 unlisted
  local cmd = merge_tables({ fd, "-HI", "-td", "--max-depth=1", "." }, search_folders)
  wezterm.log_info "cmd: "
  wezterm.log_info(cmd)

  for _, value in ipairs(cmd) do
    wezterm.log_info(value)
  end
  local success, stdout, stderr = wezterm.run_child_process(cmd)

  if not success then
    wezterm.log_error("Failed to run fd: " .. stderr)
    return
  end

  for line in stdout:gmatch "([^\n]*)\n?" do
    local project = normalize_path(line)
    local label = project
    local id = project
    table.insert(projects, { label = tostring(label), id = tostring(id) })
  end

  window:perform_action(
    act.InputSelector {
      action = wezterm.action_callback(function(win, _, id, label)
        if not id and not label then
          wezterm.log_info "Cancelled"
        else
          wezterm.log_info("Selected " .. label)
          win:perform_action(
            act.SwitchToWorkspace { name = id, spawn = { cwd = label } },
            pane
          )
        end
      end),
      fuzzy = true,
      title = "Select project",
      choices = projects,
    },
    pane
  )
end

return M
```

**Comment by sravioli** [comment]
Yup we could use fd!

**Comment by akthe-at** [comment]
Looks like we still have to move towards caching the contents into the GLOBAL because even in my above example it uses wt.run_child_process() which will fail in the same way as wt.read_dir :\  using dir, fd, find seems to be interchangeable...the killer is having to open multiple cmd prompts with io.popen(). Argh.

**Comment by sravioli** [comment]
> Looks like we still have to move towards caching the contents into the GLOBAL because even in my above example it uses wt.run_child_process() which will fail in the same way as wt.read_dir :\  using dir, fd, find seems to be interchangeable...the killer is having to open multiple cmd prompts with io.popen(). Argh.

Aw dang it. I don't think that using fd would be any faster. We could read and register the lists once at startup to cause minimal popups. I honestly can't think of anything else to solve this problem.

`io.open()` does not seem to open any popup but idk how to use it to replace `io.popen()`

**Comment by sravioli** [comment]
Although we could use `os.execute()` to execute the command and pipe the output to a file and then read its contents with `io.open()`. If I recall correctly the latter does not cause any screen flashes (I use it for getting the nearest git root of a directory)

**Comment by akthe-at** [comment]
I hadn't considered actually writing to a temp file to read...would you leave it be or clean it up every time? I hadn't thought too much about os.execute because i saw that it didn't return stdout but the temp file would negate that issue!

**Comment by sravioli** [comment]
> I hadn't considered actually writing to a temp file to read...would you leave it be or clean it up every time? I hadn't thought too much about os.execute because i saw that it didn't return stdout but the temp file would negate that issue!

I think it would be best to remove it, I don't think it serves any other purpose other than redirecting stdout

**Comment by sravioli** [comment]
@akthe-at Few hours ago (I couldn't let you know earlier since I was in a hurry) I pushed a commit to the new branch that implements the piping of the command output to a temp file.  For what I've tested on Win11 looks like it works. I haven't implemented the `wt.GLOBAL` caching still.

**Comment by akthe-at** [comment]
I'm pretty excited to try it out tonight, spent Friday evening trying to get something to with to no avail and then spent the rest of the weekend working on building a fence in my yard...🤣🤣

**Comment by sravioli** [comment]
> I'm pretty excited to try it out tonight, spent Friday evening trying to get something to with to no avail and then spent the rest of the weekend working on building a fence in my yard...🤣🤣

Lmk what you think! It's not perfect but it looks like it works. I'll improve it tomorrow :)

**Comment by akthe-at** [comment]
Smooth as silk now

**Comment by sravioli** [comment]
I've come across the following: upon system restart, or when removing the temp files created by `M.fs.read_dir()` and relaunching Wezterm I get an error. Reloading the config seems to fix it.

Also, adding a call to `os.remove(tempfile)` in `M.fs.read_dir()` results in an infinite loop for some reason...

**Comment by akthe-at** [comment]
I did notice some funky ness when adding new assets today when I was getting a picker setup again for fonts and for line height (font leading)...I wasn't sure about trying to add them back in on here until you were more stable with how you wanted to approach. It seems like we might really need to figure out that temp file vs GLOBAL, etc before having to rewrite everything again  ^_^

**Comment by sravioli** [comment]
I think I've fixed it! I was opening/creating the file wrong we're now correctly using `GLOBAL`.

**Comment by akthe-at** [comment]
@sravioli I feel like the key here might be using either wt.run_child_process instead of os.execute() but my own tinkering/attempts have not been succesful.

Here is a [discussion](https://github.com/wez/wezterm/discussions/1632) about its use.

[Here are the](https://wezfurlong.org/wezterm/config/lua/wezterm/run_child_process.html) docs

**Comment by sravioli** [comment]
> @sravioli I feel like the key here might be using either wt.run_child_process instead of os.execute() but my own tinkering/attempts have not been succesful.
> 
> Here is a [discussion](https://github.com/wez/wezterm/discussions/1632) about its use.
> 
> [Here are the](https://wezfurlong.org/wezterm/config/lua/wezterm/run_child_process.html) docs

Thanks :) 
I'll look into this and see if it works

**Comment by sravioli** [comment]
@akthe-at As a last resort (before switching to `wt.run_child_process()`, I've pushed another commit to #10 that seems to solve the popup issue on Win11

**Comment by akthe-at** [comment]
@sravioli back to being smooth as silk!

**Comment by sravioli** [comment]
Yay!
